import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'


export default function Home() {

  return (
    <div className='bg-gray-900 text-white min-h-screen min-w-screen'>
      <Head>
        <title>Barbershop Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      {/* check for user when app loads. if no user, show landing page with Login/Signup buttons. */}

        
    </div>
  )
}

// SSR API EXAMPLE 
 // const products = await fetch('https://60fa477f7ae59c001716606b.mockapi.io/products')
  //   .then(res => res.json());
  //
  // return {
  //   props: {
  //     products,
  //   }
  // }